### ISSUE TITLE
Can't run client

### ISSUE THREAD

**Issue by definitio** [ThunderEX/py-kms#32]
```
$ python client.py localhost
Connecting to localhost on port 1688...
Traceback (most recent call last):
  File "client.py", line 239, in <module>
    main()
  File "client.py", line 63, in main
    kmsRequest = createKmsRequest()
  File "client.py", line 195, in createKmsRequest
    handler = kmsRequestV4(None, config)
  File "/kms/kmsBase.py", line 122, in __init__
    if self.config['sqlite'] and self.config['dbSupport']:
KeyError: 'sqlite'
```

**Comment by ThunderEX** [comment]
- Are you using CPython or pypy or micropython?
- What's the version of your Python?

**Comment by JonnyTech** [comment]
Are you running both server and client on the same computer?

**Comment by definitio** [comment]
I'm using docker, so it's CPython 2.7.15. I tried to run client from container and from host (CPython 3.6.7).

**Comment by ThunderEX** [comment]
Hi @definitio 
Please check whether the new commit fix your problem.

**Comment by definitio** [comment]
It works. Thank you!
